### ISSUE TITLE
Build fails from zip file URL returning '404 Not Found' error

### ISSUE THREAD

**Issue by wendychu** [tenonedesign/T1Autograph-SP#1]
The https://tenonedesign.com/media/T1Autograph-2.0.6.zip URL referenced in [Package.swift](https://github.com/tenonedesign/T1Autograph-SP/blob/6132fc28edb4364dfa4bbad550f19b8bce0fc650/Package.swift#L18C19-L18C71) is returning a `404 Not Found` error. May I suggest including the zip file into the Github repo so that it can be referenced locally?

**Comment by peter-laurens** [comment]
We are also experiencing this issue.

**Comment by tenonedesign** [comment]
Thanks so much for the report!  This has been resolved on the server, and we’ll look at including in the repo for the next point release.
