### ISSUE TITLE
Unable to submit app for Xcode 16

### ISSUE THREAD

**Issue by mzeeshanid** [tenonedesign/T1Autograph-SP#2]
We are using the T1Autograph library in our app and we are unable to submit new builds to appstore. This library comes in a precompiled format and has enabled bitcode which is no longer accepted by the appstore. Recompile the framework without bitcode enabled and roll out a new version.
Thanks
<img width="729" alt="Screenshot 2024-10-07 at 11 00 53 AM" src="https://github.com/user-attachments/assets/4a30771e-327d-4a0e-89c6-67c0e138f20d">

**Comment by tenonedesign** [comment]
Thanks for the report!  Bitcode has been stripped in version 2.0.7.
